# Generated by Django 2.2.1 on 2019-05-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks',
            name='description',
        ),
    ]
