# Generated by Django 2.2.1 on 2019-05-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_drinks_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deserts',
            name='photo',
            field=models.ImageField(upload_to='templates/img/deserts_images/'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='photo',
            field=models.ImageField(upload_to='templates/img/drinks_images/'),
        ),
        migrations.AlterField(
            model_name='pizzas',
            name='photo',
            field=models.ImageField(upload_to='templates/img/pizza_images/'),
        ),
    ]
