# Generated by Django 2.2.1 on 2019-05-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20190525_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzas',
            name='photo',
        ),
    ]
