# Generated by Django 2.2.1 on 2019-05-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_pizzas_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzas',
            name='photo',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='templates/img/pizza_images/'),
        ),
    ]
