# Generated by Django 2.2.1 on 2019-05-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_pizzas_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deserts',
            name='photo',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='templates/img/deserts_images/'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='photo',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='templates/img/drinks_images/'),
        ),
    ]
