# Generated by Django 2.2.1 on 2019-05-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20190525_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deserts',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
