# Generated by Django 2.2.1 on 2019-05-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20190525_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deserts',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='pizzas',
            name='photo',
        ),
    ]
