# Generated by Django 2.2.1 on 2019-05-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20190525_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='deserts',
            name='photo',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='templates/img/deserts_images/'),
        ),
        migrations.AddField(
            model_name='drinks',
            name='photo',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='templates/img/drinks_images/'),
        ),
        migrations.AddField(
            model_name='pizzas',
            name='photo',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='templates/img/pizza_images/'),
        ),
    ]
