# Generated by Django 2.2.1 on 2019-05-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20190525_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deserts',
            name='photo',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='photo',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pizzas',
            name='photo',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pizzas',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
