# Generated by Django 2.1.5 on 2019-05-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20190525_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePizzas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=20)),
                ('Моцарелла', models.BooleanField(default=False)),
                ('Подвійний сир', models.BooleanField(default=False)),
                ('Бекон ', models.BooleanField(default=False)),
                ('Курка ', models.BooleanField(default=False)),
                ('Шинка', models.BooleanField(default=False)),
                ('Зелень', models.BooleanField(default=False)),
                ('Ананас', models.BooleanField(default=False)),
                ('Оливки ', models.BooleanField(default=False)),
                ('Помідори', models.BooleanField(default=False)),
                ('Мариновані огірки', models.BooleanField(default=False)),
                ('Перець', models.BooleanField(default=False)),
                ('Шампіньйони', models.BooleanField(default=False)),
                ('Кукурудза', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='pizzas',
            name='photo',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='images/'),
        ),
    ]
