# Generated by Django 2.2.1 on 2019-05-25 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20190526_0131'),
        ('menu', '0010_auto_20190526_0110'),
    ]

    operations = [
    ]
