# Generated by Django 2.2.1 on 2019-05-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_merge_20190526_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDeserts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=20)),
                ('phone_number', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDrinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=20)),
                ('phone_number', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPizzas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=20)),
                ('phone_number', models.TextField(max_length=20)),
            ],
        ),
    ]
