# Generated by Django 2.2.1 on 2019-05-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_orderdeserts_orderdrinks_orderpizzas'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpizzas',
            name='phone_number',
            field=models.TextField(default=0, max_length=20),
        ),
    ]
