# Generated by Django 2.2.1 on 2019-05-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_createpizzas_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpizzas',
            name='phone_number',
            field=models.TextField(default=None, max_length=20),
        ),
    ]
